# Question

Look at this function:

```js
const bailOut = () => {
  for (let i = 0; i < 5; i++) {
    if (i > 3) return;
    console.log("Inside the loop", i);
  }
  console.log("Outside the loop");
};
```

Is that `console.log('Outside the loop');` ever going to run? Why or why not?

# Answer

The `console.log` outside the loop is never going to run because the loop has the `return` keyword that will always run.

# Teacher Feedback
